sonar.projectKey=emsi99_PFA_Pointage
sonar.organization=emsi99
sonar.sources=app,lib,models
sonar.exclusions=**/*.test.ts,**/node_modules/**,**/.next/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info